
name: Browser Tests And Coverage

on:
  push:
    branches: [ master ]

  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  tests:
    name: Unit Tests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: [12, 14, 16]

    steps:
      - uses: actions/checkout@v2

      - name: Setup Chrome
        uses: browser-actions/setup-chrome@latest
        with:
          chrome-version: stable

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.4.0
        with:
          node-version: "${{ matrix.node }}"

#      - id: yarn-cache-dir-path
#        run: echo "::set-output name=dir::$(yarn cache dir)"
#      - name: Setup Cache
#        uses: actions/cache@v1
#        with:
#          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
#          key: yarn-${{ hashFiles('yarn.lock') }}
#          restore-keys: |
#            yarn-

#      - name: Install Dependencies
#        run: yarn --frozen-lockfile

      - name: Run Tests
        run: |
          npm ci
          npm run api-doc:test

      - name: Register CodeCov
        uses: codecov/codecov-action@v1
        with:
          file: coverage/lcov.info
          flags: unit

      - uses: actions/upload-artifact@v2
        with:
          name: test-videos
          path: test-videos
        if: ${{ always() }}

#  browsers:
#    name: Browser Tests
#    runs-on: ubuntu-latest
#
#    env:
#      BROWSER_PROVIDER_READY_FILE: /tmp/sauce-connect-ready
#      LOGS_DIR: /tmp/logs
#
#    steps:
#      - uses: actions/checkout@v2
#
#      - name: Saucelabs Connect
#        run: |
#          mkdir -p $LOGS_DIR
#          ./scripts/sauce_connect_setup.sh
#        timeout-minutes: 2
#
#      - name: Wait for Sauce Connect
#        uses: ifaxity/wait-on-action@v1
#        with:
#          resource: "file:${{ env.BROWSER_PROVIDER_READY_FILE }}"
#        timeout-minutes: 2
#
#      - name: Saucelabs Connect
#        uses: saucelabs/sauce-connect-action@v1
#        with:
#          username: "${{ secrets.SAUCE_USERNAME }}"
#          accessKey: "${{ secrets.SAUCE_ACCESS_KEY }}"
#          tunnelIdentifier: "${{ github.run_id }}"
#          scVersion: 4.6.3
#
#      - name: Setup Node.js environment
#        uses: actions/setup-node@v2.4.0
#        with:
#          node-version: "14.x"
#
#      - id: yarn-cache-dir-path
#        run: echo "::set-output name=dir::$(yarn cache dir)"
#      - name: Setup Cache
#        uses: actions/cache@v1
#        with:
#          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
#          key: yarn-${{ hashFiles('yarn.lock') }}
#          restore-keys: |
#            yarn-
#
#      - name: Install Dependencies
#        run: yarn --frozen-lockfile
#
#      - name: Run Browser Tests
#        run: |
#          yarn saucelabs
#          yarn saucelabs:ie
#
#      - uses: actions/upload-artifact@v2
#        with:
#          name: test-videos
#          path: test-videos
#        if: ${{ always() }}
#
#      - name: Saucelabs Disconnect
#        run: ./scripts/sauce_connect_teardown.sh
#        if: ${{ always() }}
