name: Test Coverage

on:
  push:
    branches:
      - master
      - '[0-9]+_[0-9]+_x'
  pull_request:
    types: [opened, synchronize, reopened]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"
      - run: npm ci --legacy-peer-deps
#      - run: npx playwright install-deps
#      - run: npx playwright install
      - run: |
          npm run ci:test
          npm run scripts:test
      - uses: codecov/codecov-action@v3
        with:
          file: coverage/lcov.info
          flags: unit
#      - uses: codecov/codecov-action@v3
#        with:
#          file: coverage-e2e/lcov.info
#          flags: e2e
      - uses: actions/upload-artifact@v3
        with:
          name: test-reports
          path: test-reports
        if: ${{ always() }}
