
name: CI Tests

on:
  pull_request:
    branches: [ master ]
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  tests:
    name: Unit Tests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: [12, 14, 16]

    steps:
      - uses: actions/checkout@v2

      - name: Setup Chrome
        uses: browser-actions/setup-chrome@latest
        with:
          chrome-version: stable

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.4.0
        with:
          node-version: "${{ matrix.node }}"

#      - id: yarn-cache-dir-path
#        run: echo "::set-output name=dir::$(yarn cache dir)"
#      - name: Setup Cache
#        uses: actions/cache@v1
#        with:
#          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
#          key: yarn-${{ hashFiles('yarn.lock') }}
#          restore-keys: |
#            yarn-

#      - name: Install Dependencies
#        run: yarn --frozen-lockfile

      - name: Run Tests
        run: |
          npm ci
          npm run api-doc:test
